name: CI

on: [pull_request]

jobs:
  Check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Gradle tests
        run: ./gradlew clean check
      - name: Run IntelliJ Inspections
        uses: gps/intellij-inspections-action@0.0.1
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Save inspection results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: idea_inspections
          path: target/idea_inspections
      - name: Save test reports
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: test_reports
          path: build/reports/tests/test/
      - name: Create fat jar
        run: ./gradlew shadowJar
      - name: Save fat jar
        uses: actions/upload-artifact@v1
        with:
          name: automatedturk.jar
          path: build/libs/automatedturk.jar
